import Head from "next/head";
import Image from "next/image";
import Catagories from "../components/FoodHome/Catagories";
import Cover from "../components/FoodHome/Cover";
import Promotion from "../components/FoodHome/Promotion";
import styles from "../styles/Home.module.css";
import MostOrdered from "../components/FoodHome/MostOrdered";
import RecommendedHomeChef from "../components/FoodHome/RecommendedHomeChef";
import RecommendedProduct from "../components/FoodHome/RecommendedProduct";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar";
import JoinAsVendorOrRider from "../components/JoinAsVendorOrRider";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lakhrifood </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Cover />
      <Catagories />
      <Promotion />
      <MostOrdered />
      <RecommendedHomeChef />

      <RecommendedProduct />
      <JoinAsVendorOrRider />
      <Footer />
    </div>
  );
}
